REPORT ZMRT_ORDER_MANAGMENT_SYSTEM.

INCLUDE ZMRT_ORDER_MANAGMENT_S_TOP.
INCLUDE ZMRT_ORDER_MANAGMENT_S_CLS.
INCLUDE ZMRT_ORDER_MANAGMENT_S_MDL.
INCLUDE ZMRT_ORDER_MANAGMENT_S_FRM.


START-OF-SELECTION.

data: sform_fm type RS38L_FNAM.

create OBJECT go_main.
create object go_main2.

  CASE 'X' .
    WHEN RB_MUS.
      go_main->START_SCREEN( ).
    WHEN RB_ORDER.
      GO_MAIN2->START_SCREEN( ).
    WHEN RB_mysip.
      go_main2->GET_MYSIP( ).
  ENDCASE.
