REPORT ZMRT_CREATE_CUSTOMER.

INCLUDE ZMRT_CREATE_CUSTOMER_TOP.
INCLUDE ZMRT_CREATE_CUSTOMER_CLS.
INCLUDE ZMRT_CREATE_CUSTOMER_MDL.
INCLUDE zmrt_create_customer_frm.

START-OF-SELECTION.


CREATE OBJECT GO_MAIN.

GO_MAIN->START_SCREEN( ).
