REPORT ZMRT_MANAGE_ORDERS.

include ZMRT_MANAGE_ORDERS_TOP.
include ZMRT_MANAGE_ORDERS_CLS.
include ZMRT_MANAGE_ORDERS_MDL.
include ZMRT_MANAGE_ORDERS_FRM.

START-OF-SELECTION.

create OBJECT go_main.

go_main->START_SCREEN( ).
